modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"
issueTrackerURL="https://github.com/Iunius118/SimpleMovableGrid/issues"

[[mods]]
modId="simplemovablegrid"
version="${file.jarVersion}"
displayName="Simple Movable Grid"
displayURL="https://github.com/Iunius118/SimpleMovableGrid"
logoFile="simplemovablegrid_logo.png"
credits="Iunius118"
authors="Iunius118"
description="Adds a simple movable grid on client"

[[dependencies.simplemovablegrid]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.simplemovablegrid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="CLIENT"
